# Generated by Django 3.0.5 on 2020-05-08 15:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_auto_20200508_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='date_published',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 5, 8, 15, 40, 51, 136420, tzinfo=utc)),
        ),
    ]
