# Generated by Django 3.0.5 on 2020-05-08 16:06

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('realtors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('adress', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zipcode', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True)),
                ('price', models.IntegerField()),
                ('bedrooms', models.IntegerField()),
                ('bathrooms', models.DecimalField(decimal_places=1, max_digits=2)),
                ('garage', models.IntegerField(default=0)),
                ('square_feet', models.IntegerField()),
                ('lot_size', models.DecimalField(decimal_places=1, max_digits=5)),
                ('image_main', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('image_1', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('image_2', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('image_3', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('image_4', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('image_5', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('image_6', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('is_published', models.BooleanField(default=True)),
                ('date_published', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('realtor_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='realtors.Realtor')),
            ],
        ),
    ]
