# Generated by Django 3.0.5 on 2020-05-08 15:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_auto_20200508_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='date_published',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
