# Generated by Django 3.0.5 on 2020-05-08 15:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_auto_20200508_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='date_published',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
